#**K Nearest Neighbour for Fruit Detection**

In [17]:
#Required Libraries
import numpy as np  
import pandas as pd 
import matplotlib.pyplot as plt 



In [18]:
#Loading the data from GOOGLE DRIVE 
dataset = pd.read_csv("/content/drive/MyDrive/fruit_dataset.csv")

In [19]:
#Showing  data
dataset


fruit_label fruit_name  mass  width  height  color_score
0             1      apple   192    8.4     7.3         0.55
1             1      apple   180    8.0     6.8         0.59
2             1      apple   176    7.4     7.2         0.60
3             2   mandarin    86    6.2     4.7         0.80
4             2   mandarin    84    6.0     4.6         0.79
5             2   mandarin    80    5.8     4.3         0.77
6             2   mandarin    80    5.9     4.3         0.81
7             2   mandarin    76    5.8     4.0         0.81
8             1      apple   178    7.1     7.8         0.92
9             1      apple   172    7.4     7.0         0.89
10            1      apple   166    6.9     7.3         0.93
11            1      apple   172    7.1     7.6         0.92
12            1      apple   154    7.0     7.1         0.88
13            1      apple   164    7.3     7.7         0.70
14            1      apple   152    7.6     7.3         0.69
15            1      apple   156    7.7     7.1         0.69
16            1      apple   156    7.6     7.5         0.67
17            1      apple   168    7.5     7.6         0.73
18            1      apple   162    7.5     7.1         0.83
19            1      apple   162    7.4     7.2         0.85
20            1      apple   160    7.5     7.5         0.86
21            1      apple   156    7.4     7.4         0.84
22            1      apple   140    7.3     7.1         0.87
23            1      apple   170    7.6     7.9         0.88
24            3     orange   342    9.0     9.4         0.75
25            3     orange   356    9.2     9.2         0.75
26            3     orange   362    9.6     9.2         0.74
27            3     orange   204    7.5     9.2         0.77
28            3     orange   140    6.7     7.1         0.72
29            3     orange   160    7.0     7.4         0.81
30            3     orange   158    7.1     7.5         0.79
31            3     orange   210    7.8     8.0         0.82
32            3     orange   164    7.2     7.0         0.80
33            3     orange   190    7.5     8.1         0.74
34            3     orange   142    7.6     7.8         0.75
35            3     orange   150    7.1     7.9         0.75
36            3     orange   160    7.1     7.6         0.76
37            3     orange   154    7.3     7.3         0.79
38            3     orange   158    7.2     7.8         0.77
39            3     orange   144    6.8     7.4         0.75
40            3     orange   154    7.1     7.5         0.78
41            3     orange   180    7.6     8.2         0.79
42            3     orange   154    7.2     7.2         0.82
43            4      lemon   194    7.2    10.3         0.70
44            4      lemon   200    7.3    10.5         0.72
45            4      lemon   186    7.2     9.2         0.72
46            4      lemon   216    7.3    10.2         0.71
47            4      lemon   196    7.3     9.7         0.72
48            4      lemon   174    7.3    10.1         0.72
49            4      lemon   132    5.8     8.7         0.73
50            4      lemon   130    6.0     8.2         0.71
51            4      lemon   116    6.0     7.5         0.72
52            4      lemon   118    5.9     8.0         0.72
53            4      lemon   120    6.0     8.4         0.74
54            4      lemon   116    6.1     8.5         0.71
55            4      lemon   116    6.3     7.7         0.72
56            4      lemon   116    5.9     8.1         0.73
57            4      lemon   152    6.5     8.5         0.72
58            4      lemon   118    6.1     8.1         0.70

Here see that apple is labbeled as 1 ..mandarin as 2..Orange is 3 and lemon is 4

In [20]:
#Showing the information about data 

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   fruit_label  59 non-null     int64  
 1   fruit_name   59 non-null     object 
 2   mass         59 non-null     int64  
 3   width        59 non-null     float64
 4   height       59 non-null     float64
 5   color_score  59 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 2.9+ KB


In [21]:
#Spliting the data into X and Y 
X = dataset[['mass','width','height','color_score']]
Y = dataset['fruit_label']

In [22]:
X

mass  width  height  color_score
0    192    8.4     7.3         0.55
1    180    8.0     6.8         0.59
2    176    7.4     7.2         0.60
3     86    6.2     4.7         0.80
4     84    6.0     4.6         0.79
5     80    5.8     4.3         0.77
6     80    5.9     4.3         0.81
7     76    5.8     4.0         0.81
8    178    7.1     7.8         0.92
9    172    7.4     7.0         0.89
10   166    6.9     7.3         0.93
11   172    7.1     7.6         0.92
12   154    7.0     7.1         0.88
13   164    7.3     7.7         0.70
14   152    7.6     7.3         0.69
15   156    7.7     7.1         0.69
16   156    7.6     7.5         0.67
17   168    7.5     7.6         0.73
18   162    7.5     7.1         0.83
19   162    7.4     7.2         0.85
20   160    7.5     7.5         0.86
21   156    7.4     7.4         0.84
22   140    7.3     7.1         0.87
23   170    7.6     7.9         0.88
24   342    9.0     9.4         0.75
25   356    9.2     9.2         0.75
26   362    9.6     9.2         0.74
27   204    7.5     9.2         0.77
28   140    6.7     7.1         0.72
29   160    7.0     7.4         0.81
30   158    7.1     7.5         0.79
31   210    7.8     8.0         0.82
32   164    7.2     7.0         0.80
33   190    7.5     8.1         0.74
34   142    7.6     7.8         0.75
35   150    7.1     7.9         0.75
36   160    7.1     7.6         0.76
37   154    7.3     7.3         0.79
38   158    7.2     7.8         0.77
39   144    6.8     7.4         0.75
40   154    7.1     7.5         0.78
41   180    7.6     8.2         0.79
42   154    7.2     7.2         0.82
43   194    7.2    10.3         0.70
44   200    7.3    10.5         0.72
45   186    7.2     9.2         0.72
46   216    7.3    10.2         0.71
47   196    7.3     9.7         0.72
48   174    7.3    10.1         0.72
49   132    5.8     8.7         0.73
50   130    6.0     8.2         0.71
51   116    6.0     7.5         0.72
52   118    5.9     8.0         0.72
53   120    6.0     8.4         0.74
54   116    6.1     8.5         0.71
55   116    6.3     7.7         0.72
56   116    5.9     8.1         0.73
57   152    6.5     8.5         0.72
58   118    6.1     8.1         0.70

In [23]:
Y

0     1
1     1
2     1
3     2
4     2
5     2
6     2
7     2
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    4
44    4
45    4
46    4
47    4
48    4
49    4
50    4
51    4
52    4
53    4
54    4
55    4
56    4
57    4
58    4
Name: fruit_label, dtype: int64

In [24]:
#Spliting the data in train and test 
from sklearn.model_selection import train_test_split

x_train ,x_test , y_train ,  y_test = train_test_split(X ,Y , test_size=.10 , random_state= 0) # test_size for separate test data 

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(53, 4)
(53,)
(6, 4)
(6,)


In [25]:
#importing the K Nearest Neighbour
from sklearn.neighbors import KNeighborsClassifier

#Intializing the KNN
knn = KNeighborsClassifier(n_neighbors = 4 , metric = "minkowski") # minkowski is used to find encludian distance 

# Fitting the model 

knn.fit(x_train , y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [26]:
#Prediction 
predict = knn.predict(x_test)



In [27]:
print(predict)

[3 3 4 3 1 1]


###Prediction with unseen data 

In [30]:
prediction1 = knn.predict([['120','7.8','6.3','8.9']])

prediction1

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:171: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_base.py:605: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')


array([4])

Above in Last line array([4]) shows that it a lemon because lemon is labelled above as 4 

In [31]:
new_prediction = knn.predict([['300','9.3','8.9','7.6']])

new_prediction

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:171: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_base.py:605: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')


array([3])

output = array([3]) shows it is orange bcz orange is labbeled 3 

In [32]:
new_prediction = knn.predict([['162'	,'7.5','7.1',	'0.83']])

new_prediction

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:171: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_base.py:605: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')


array([1])

output = array([1]) shows it is Apple Bcz Apple is labbeled 1